name: Simple Python Code Analysis

on: [ push, pull_request ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run linters
        run: make lint

      - name: Run all tests
        run: make test
